services:
  # Backend (Node.js + Express)
  backend:
    build: ./backend
    container_name: beyblade-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb+srv://shlatiz07_db_user:Scheidet13@cluster0.brryzwm.mongodb.net/beyblade-arena?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=tu_super_secreto_jwt_cambiar_en_produccion
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - beyblade-network

  # Frontend (React + Nginx)
  frontend:
    build: ./frontend
    container_name: beyblade-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - beyblade-network

networks:
  beyblade-network:
    driver: bridge